name = "mundial2026"
main = "worker.js"
compatibility_date = "2024-01-01"

[placement]
mode = "smart"

routes = [
  { pattern = "mejortercero.online/*", zone_name = "mejortercero.online" },
  { pattern = "www.mejortercero.online/*", zone_name = "mejortercero.online" }
]
